version: '3'
services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: cards
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"


  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
